// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: homeit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Created string `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated string `protobuf:"bytes,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Role    string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Expires string `protobuf:"bytes,6,opt,name=expires,proto3" json:"expires,omitempty"`
}

func (x *GetUserSession) Reset() {
	*x = GetUserSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homeit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSession) ProtoMessage() {}

func (x *GetUserSession) ProtoReflect() protoreflect.Message {
	mi := &file_homeit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSession.ProtoReflect.Descriptor instead.
func (*GetUserSession) Descriptor() ([]byte, []int) {
	return file_homeit_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserSession) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *GetUserSession) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *GetUserSession) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserSession) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

var File_homeit_proto protoreflect.FileDescriptor

var file_homeit_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x6f, 0x6d, 0x65, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x42, 0x54, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x70, 0x69, 0x6f, 0x72, 0x6f, 0x77, 0x73, 0x6b, 0x69, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_homeit_proto_rawDescOnce sync.Once
	file_homeit_proto_rawDescData = file_homeit_proto_rawDesc
)

func file_homeit_proto_rawDescGZIP() []byte {
	file_homeit_proto_rawDescOnce.Do(func() {
		file_homeit_proto_rawDescData = protoimpl.X.CompressGZIP(file_homeit_proto_rawDescData)
	})
	return file_homeit_proto_rawDescData
}

var file_homeit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_homeit_proto_goTypes = []interface{}{
	(*GetUserSession)(nil), // 0: proto.GetUserSession
}
var file_homeit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_homeit_proto_init() }
func file_homeit_proto_init() {
	if File_homeit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_homeit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_homeit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_homeit_proto_goTypes,
		DependencyIndexes: file_homeit_proto_depIdxs,
		MessageInfos:      file_homeit_proto_msgTypes,
	}.Build()
	File_homeit_proto = out.File
	file_homeit_proto_rawDesc = nil
	file_homeit_proto_goTypes = nil
	file_homeit_proto_depIdxs = nil
}
